version: '3'
services:
  hub:
    image: selenium/hub:3.14
    ports:
      - "4444:4444"
  chrome:
    image: selenium/node-chrome:3.14
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  firefox:
    image: selenium/node-firefox:3.14
    shm_size: '1gb'
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub  
  smoketest:
    image: jmorah/selenium-dockerz
    depends_on:
      - chrome

    environment:
      - BROWSER=chrome
      - HUB_HOST=hub
      - SUITE=smoketest.xml
    volumes:
      - ./output/smoketest:/usr/share/automation/test-output

  signupregression:
    image: jmorah/selenium-dockerz
    depends_on:
      - chrome

    environment:
      - BROWSER=chrome
      - HUB_HOST=hub
      - SUITE=smoketest.xml
    volumes:
      - ./output/signupregression:/usr/share/automation/test-output
  automation3:
    image: jmorah/selenium-dockerz
    depends_on:
      - chrome
      - firefox
    environment:
      - BROWSER=chrome
      - HUB_HOST=hub
      - SUITE=dockertest2.xml
    volumes:
      - ./output/automation3:/usr/share/automation/test-output

  automation4:
    image: jmorah/selenium-dockerz
    depends_on:
      - chrome
      - firefox
    environment:
      - BROWSER=firefox
      - HUB_HOST=hub
      - SUITE=dockertest2.xml
    volumes:
      - ./output/automation4:/usr/share/automation/test-output
